export const firstNames = [
  'Abigail',
  'Alexandra',
  'Alison',
  'Amanda',
  'Amelia',
  'Amy',
  'Andrea',
  'Angela',
  'Anna',
  'Anne',
  'Audrey',
  'Ava',
  'Bella',
  'Bernadette',
  'Carol',
  'Caroline',
  'Carolyn',
  'Chloe',
  'Claire',
  'Deirdre',
  'Diana',
  'Diane',
  'Donna',
  'Dorothy',
  'Elizabeth',
  'Ella',
  'Emily',
  'Emma',
  'Faith',
  'Felicity',
  'Fiona',
  'Gabrielle',
  'Grace',
  'Hannah',
  'Heather',
  'Irene',
  'Jan',
  'Jane',
  'Jasmine',
  'Jennifer',
  'Jessica',
  'Joan',
  'Joanne',
  'Julia',
  'Karen',
  'Katherine',
  'Kimberly',
  'Kylie',
  'Lauren',
  'Leah',
  'Lillian',
  'Lily',
  'Lisa',
  'Madeleine',
  'Maria',
  'Mary',
  'Megan',
  'Melanie',
  'Michelle',
  'Molly',
  'Natalie',
  'Nicola',
  'Olivia',
  'Penelope',
  'Pippa',
  'Rachel',
  'Rebecca',
  'Rose',
  'Ruth',
  'Sally',
  'Samantha',
  'Sarah',
  'Sonia',
  'Sophie',
  'Stephanie',
  'Sue',
  'Theresa',
  'Tracey',
  'Una',
  'Vanessa',
  'Victoria',
  'Virginia',
  'Wanda',
  'Wendy',
  'Yvonne',
  'Zoe',
  'Adam',
  'Adrian',
  'Alan',
  'Alexander',
  'Andrew',
  'Anthony',
  'Austin',
  'Benjamin',
  'Blake',
  'Boris',
  'Brandon',
  'Brian',
  'Cameron',
  'Carl',
  'Charles',
  'Christian',
  'Christopher',
  'Colin',
  'Connor',
  'Dan',
  'David',
  'Dominic',
  'Dylan',
  'Edward',
  'Eric',
  'Evan',
  'Frank',
  'Gavin',
  'Gordon',
  'Harry',
  'Ian',
  'Isaac',
  'Jack',
  'Jacob',
  'Jake',
  'James',
  'Jason',
  'Joe',
  'John',
  'Jonathan',
  'Joseph',
  'Joshua',
  'Julian',
  'Justin',
  'Keith',
  'Kevin',
  'Leonard',
  'Liam',
  'Lucas',
  'Luke',
  'Matt',
  'Max',
  'Michael',
  'Nathan',
  'Neil',
  'Nicholas',
  'Oliver',
  'Owen',
  'Paul',
  'Peter',
  'Phil',
  'Piers',
  'Richard',
  'Robert',
  'Ryan',
  'Sam',
  'Sean',
  'Sebastian',
  'Simon',
  'Stephen',
  'Steven',
  'Stewart',
  'Thomas',
  'Tim',
  'Trevor',
  'Victor',
  'Warren',
  'William',
];
export const lastNames = [
  'Abraham',
  'Allan',
  'Alsop',
  'Anderson',
  'Arnold',
  'Avery',
  'Bailey',
  'Baker',
  'Ball',
  'Bell',
  'Berry',
  'Black',
  'Blake',
  'Bond',
  'Bower',
  'Brown',
  'Buckland',
  'Burgess',
  'Butler',
  'Cameron',
  'Campbell',
  'Carr',
  'Chapman',
  'Churchill',
  'Clark',
  'Clarkson',
  'Coleman',
  'Cornish',
  'Davidson',
  'Davies',
  'Dickens',
  'Dowd',
  'Duncan',
  'Dyer',
  'Edmunds',
  'Ellison',
  'Ferguson',
  'Fisher',
  'Forsyth',
  'Fraser',
  'Gibson',
  'Gill',
  'Glover',
  'Graham',
  'Grant',
  'Gray',
  'Greene',
  'Hamilton',
  'Hardacre',
  'Harris',
  'Hart',
  'Hemmings',
  'Henderson',
  'Hill',
  'Hodges',
  'Howard',
  'Hudson',
  'Hughes',
  'Hunter',
  'Ince',
  'Jackson',
  'James',
  'Johnston',
  'Jones',
  'Kelly',
  'Kerr',
  'King',
  'Knox',
  'Lambert',
  'Langdon',
  'Lawrence',
  'Lee',
  'Lewis',
  'Lyman',
  'MacDonald',
  'Mackay',
  'Mackenzie',
  'MacLeod',
  'Manning',
  'Marshall',
  'Martin',
  'Mathis',
  'May',
  'McDonald',
  'McLean',
  'McGrath',
  'Metcalfe',
  'Miller',
  'Mills',
  'Mitchell',
  'Morgan',
  'Morrison',
  'Murray',
  'Nash',
  'Newman',
  'Nolan',
  'North',
  'Ogden',
  'Oliver',
  'Paige',
  'Parr',
  'Parsons',
  'Paterson',
  'Payne',
  'Peake',
  'Peters',
  'Piper',
  'Poole',
  'Powell',
  'Pullman',
  'Quinn',
  'Rampling',
  'Randall',
  'Rees',
  'Reid',
  'Roberts',
  'Robertson',
  'Ross',
  'Russell',
  'Rutherford',
  'Sanderson',
  'Scott',
  'Sharp',
  'Short',
  'Simpson',
  'Skinner',
  'Slater',
  'Smith',
  'Springer',
  'Stewart',
  'Sutherland',
  'Taylor',
  'Terry',
  'Thomson',
  'Tucker',
  'Turner',
  'Underwood',
  'Vance',
  'Vaughan',
  'Walker',
  'Wallace',
  'Walsh',
  'Watson',
  'Welch',
  'White',
  'Wilkins',
  'Wilson',
  'Wright',
  'Young',
];
export const technologies = [
  {
    name: 'Elasticsearch',
    description:
      'Elasticsearch is a search engine based on the Lucene library. It provides a distributed, multitenant-capable full-text search engine with an HTTP web interface and schema-free JSON documents.',
  },
  {
    name: 'Apache Solr',
    description:
      'Solr is an open-source enterprise-search platform, written in Java, from the Apache Lucene project. Its major features include full-text search, hit highlighting, faceted search, real-time indexing, dynamic clustering, database integration, NoSQL features and rich document handling.',
  },
  {
    name: 'Node.js',
    description:
      'Solr is an open-source enterprise-search platform, written in Java, from the Apache Lucene project. Its major features include full-text search, hit highlighting, faceted search, real-time indexing, dynamic clustering, database integration, NoSQL features and rich document handling.',
  },
  {
    name: 'PHP',
    description:
      'PHP is a general-purpose scripting language especially suited to web development. It was originally created by Danish-Canadian programmer Rasmus Lerdorf in 1994.',
  },
  {
    name: 'Java',
    description:
      'Java is a class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.',
  },
  {
    name: 'Python',
    description:
      "Python is an interpreted, high-level and general-purpose programming language. Python's design philosophy emphasizes code readability with its notable use of significant indentation.",
  },
  {
    name: 'Swift',
    description:
      'Swift is a general-purpose, multi-paradigm, compiled programming language developed by Apple Inc. and the open-source community, first released in 2014.',
  },
  {
    name: 'React Native',
    description:
      "React Native is an open-source mobile application framework created by Facebook, Inc. It is used to develop applications for Android, Android TV, iOS, macOS, tvOS, Web, Windows and UWP by enabling developers to use React's framework along with native platform capabilities.",
  },
  {
    name: 'Flutter',
    description:
      'Flutter is an open-source UI software development kit created by Google. It is used to develop applications for Android, iOS, Linux, Mac, Windows, Google Fuchsia, and the web from a single codebase. ',
  },
  {
    name: 'Ionic',
    description:
      'Ionic is a complete open-source SDK for hybrid mobile app development created by Max Lynch, Ben Sperry, and Adam Bradley of Drifty Co. in 2013.',
  },
  {
    name: 'Angular',
    description:
      'Angular is a TypeScript-based open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations.',
  },
  {
    name: 'React',
    description:
      'React is an open-source, front end, JavaScript library for building user interfaces or UI components. It is maintained by Facebook and a community of individual developers and companies. React can be used as a base in the development of single-page or mobile applications.',
  },
  {
    name: 'Vue.js',
    description:
      'Vue.js is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications.',
  },
  {
    name: 'TypeScript',
    description:
      'TypeScript is a programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript and adds optional static typing to the language. TypeScript is designed for the development of large applications and transcompiles to JavaScript.',
  },
  {
    name: 'Magento',
    description:
      'Magento is an open-source e-commerce platform written in PHP. It uses multiple other PHP frameworks such as Laminas and Symfony.',
  },
  {
    name: 'Shopify',
    description:
      'Shopify Inc. is a Canadian multinational e-commerce company headquartered in Ottawa, Ontario. It is also the name of its proprietary e-commerce platform for online stores and retail point-of-sale systems.',
  },
  {
    name: 'SAP Hybris',
    description:
      'SAP Hybris solutions were integrated under the SAP masterbrand into the wider SAP Customer Experience portfolio',
  },
  {
    name: 'Liferay',
    description:
      'Build portals, intranets, websites and connected experiences on the most extensible digital experience platform around.',
  },
  {
    name: 'WordPress',
    description:
      'WordPress is a free and open-source content management system written in PHP and paired with a MySQL or MariaDB database. Features include a plugin architecture and a template system, referred to within WordPress as Themes.',
  },
  {
    name: 'Umbraco',
    description:
      'Umbraco is an open-source content management system platform for publishing content on the World Wide Web and intranets. It is written in C# and deployed on Microsoft based infrastructure.',
  },
  {
    name: 'Drupal',
    description:
      'Drupal is a free and open-source web content management framework written in PHP and distributed under the GNU General Public License. Drupal provides a back-end framework for at least 12% of the top 10,000 websites worldwide – ranging from personal blogs to corporate, political, and government sites.',
  },
  {
    name: 'Amazon Web Services',
    description:
      'Drupal is a free and open-source web content management framework written in PHP and distributed under the GNU General Public License. Drupal provides a back-end framework for at least 12% of the top 10,000 websites worldwide – ranging from personal blogs to corporate, political, and government sites.',
  },
  {
    name: 'Google Cloud Platform',
    description:
      'Google Cloud Platform, offered by Google, is a suite of cloud computing services that runs on the same infrastructure that Google uses internally for its end-user products, such as Google Search, Gmail, file storage, and YouTube.',
  },
  {
    name: 'Microsoft Azure',
    description:
      'Microsoft Azure, commonly referred to as Azure, is a cloud computing service created by Microsoft for building, testing, deploying, and managing applications and services through Microsoft-managed data centers.',
  },
  {
    name: 'Selenium',
    description:
      'Selenium is a portable framework for testing web applications. Selenium provides a playback tool for authoring functional tests without the need to learn a test scripting language.',
  },
  {
    name: 'MySQL',
    description:
      'MySQL is an open-source relational database management system.',
  },
  {
    name: 'Amazon DynamoDB',
    description:
      'Amazon DynamoDB is a fully managed proprietary NoSQL database service that supports key-value and document data structures and is offered by Amazon.com as part of the Amazon Web Services portfolio.',
  },
  {
    name: 'PostgreSQL',
    description:
      'PostgreSQL, also known as Postgres, is a free and open-source relational database management system emphasizing extensibility and SQL compliance.',
  },
  {
    name: 'Oracle Database',
    description:
      'Oracle Database is a multi-model database management system produced and marketed by Oracle Corporation. It is a database commonly used for running online transaction processing, data warehousing and mixed database workloads.',
  },
  {
    name: 'Firebase',
    description:
      "Firebase is Google's mobile platform that helps you quickly develop high-quality apps and grow your business.",
  },
  {
    name: 'MongoDB',
    description:
      'MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas.',
  },
];
export const allocation = [
  { name: 'Full Time', description: 'Full Time' },
  { name: 'Partially Occupied', description: 'Partially Occupied' },
  { name: 'Support', description: 'Support' },
  { name: 'On Demand', description: 'On Demand' },
];
export const designation = [
  { name: 'Mobile App Developer', description: 'Mobile App Developer' },
  { name: 'Liferay Developer', description: 'Liferay Developer' },
  { name: 'IOS App Developer', description: 'IOS App Developer' },
  { name: 'Android App Developer', description: 'Android App Developer' },
  { name: 'Java Developer', description: 'Java Developer' },
  { name: 'Python Developer', description: 'Python Developer' },
  { name: 'Angular Developer', description: 'Angular Developer' },
  { name: 'Laravel Developer', description: 'Laravel Developer' },
  { name: 'ReactJS Developer', description: 'ReactJS Developer' },
  { name: 'NodeJS Developer', description: 'NodeJS Developer' },
  { name: 'Full Stack Developer', description: 'Full Stack Developer' },
];
export const payment = [
  { name: 'Hourly', description: 'Hourly' },
  { name: 'Fixed', description: 'Fixed' },
];
export const projectpriority = [
  { name: 'High', description: 'High' },
  { name: 'Medium', description: 'Medium' },
  { name: 'Low', description: 'Low' },
];
export const projectstatus = [
  { name: 'On Track', description: 'On Track' },
  { name: 'On Hold', description: 'On Hold' },
  { name: 'Done', description: 'Done' },
  { name: 'Ready', description: 'Ready' },
  { name: 'Off Track', description: 'Off Track' },
  { name: 'Blocked', description: 'Blocked' },
  { name: 'Critical', description: 'Critical' },
  { name: 'Delayed', description: 'Delayed' },
];
export const currency = [
  { name: 'INR', description: 'Indian rupee' },
  { name: 'USD', description: 'United States Dollar' },
];
export const taskstatus = [
  { name: 'New', description: 'New' },
  { name: 'In Progress', description: 'In Progress' },
  { name: 'Developed', description: 'Developed' },
  { name: 'On hold', description: 'On hold' },
  { name: 'Rejected', description: 'Rejected' },
];
export const taskpriority = [
  { name: 'Low', description: 'Low' },
  { name: 'Medium', description: 'Medium' },
  { name: 'High', description: 'High' },
  { name: 'Immediate', description: 'Immediate' },
];
export const projectrole = [
  { name: 'Senior Team Leader', description: 'Senior Team Leader' },
  { name: 'Team Leader', description: 'Team Leader' },
  { name: 'Associate Developer', description: 'Associate Developer' },
  { name: 'Associate Team Leader', description: 'Associate Team Leader' },
  {
    name: 'Associate Project Manager',
    description: 'Associate Project Manager',
  },
  { name: 'Software Developer', description: 'Software Developer' },
  {
    name: 'Senior Software Developer',
    description: 'Senior Software Developer',
  },
  { name: 'Project Manager', description: 'Project Manager' },
  { name: 'Senior Project Manager', description: 'Senior Project Manager' },
  { name: 'SCRUM Master', description: 'SCRUM Master' },
];
export const activity = [
  { name: 'Development', description: 'Development' },
  { name: 'Support', description: 'Support' },
  { name: 'Meeting', description: 'Meeting' },
  { name: 'Assist', description: 'Assist' },
  { name: 'Design', description: 'Design' },
  { name: 'Other', description: 'Other' },
];
export const resourcestatus = [
  { name: 'Occupied', description: 'Occupied' },
  { name: 'Partially Occupied', description: 'Partially Occupied' },
  { name: 'Free', description: 'Free' },
  { name: 'On Leave', description: 'On Leave' },
];
export const teams = [
  { name: 'Python Team', description: 'Python Team' },
  { name: 'Angular Team', description: 'Angular Team' },
  { name: 'Java Team', description: 'Java Team' },
  { name: 'Android Team', description: 'Android Team' },
  { name: 'UX & UI Team', description: 'UX & UI Team' },
  { name: 'QA', description: 'QA' },
];

export const roles = [
  {
    name: 'Software Developer',
    description: 'Software Developer',
    type: 'EMP',
    code: 'SD',
  },
  {
    name: 'Senior Software Developer',
    description: 'Senior Software Developer',
    type: 'EMP',
    code: 'SSD',
  },
  { name: 'Team Leader', description: 'Team Leader', type: 'TL', code: 'TL' },
  {
    name: 'Project Manager',
    description: 'Project Manager',
    type: 'PM',
    code: 'PM',
  },
  {
    name: 'Super Admin',
    description: 'Super Admin',
    type: 'ADMIN',
    code: 'ADMIN',
  },
  { name: 'HR', description: 'HR', type: 'HR', code: 'HR' },
];
